# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/thor/02203-Design-af-digitale-systemer-/acc_inv/acc_inv.cache/wt [current_project]
set_property parent.project_path /home/thor/02203-Design-af-digitale-systemer-/acc_inv/acc_inv.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/thor/02203-Design-af-digitale-systemer-/acc_inv/acc_inv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/thor/02203-Design-af-digitale-systemer-/task3/types.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task2/acc2_inverter.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/clock_divider.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/controller.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/debounce.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/memory3_be.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/uart.vhd
  /home/thor/02203-Design-af-digitale-systemer-/task3/top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/thor/02203-Design-af-digitale-systemer-/task3/Nexys4DDR_edge.xdc
set_property used_in_implementation false [get_files /home/thor/02203-Design-af-digitale-systemer-/task3/Nexys4DDR_edge.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
